// remapgen generates the tables that turn the ids of the newest protocol (the one the server works
// in) into the ids of an older protocol, from Mojang's reports of both versions:
//
//   - packet ids per phase (clientbound: new id -> old id, serverbound: old id -> new id), by name;
//   - block states (new -> old), by block name and properties;
//   - every built-in registry (new -> old), by entry name.
//
// Content the old version doesn't have falls back to something close with the same shape (fallback
// below), or to -1 (not sent).
//
//	go run ./cmd/remapgen -old 26.2/reports -new 26.3/reports -out v776/remap_gen.go -pkg v776
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type packetsReport map[string]map[string]map[string]struct {
	ID int32 `json:"protocol_id"`
}

type blocksReport map[string]struct {
	States []struct {
		ID         int32             `json:"id"`
		Default    bool              `json:"default"`
		Properties map[string]string `json:"properties"`
	} `json:"states"`
}

type registriesReport map[string]struct {
	Entries map[string]struct {
		ID int32 `json:"protocol_id"`
	} `json:"entries"`
}

func load(dir, file string, v any) {
	b, err := os.ReadFile(filepath.Join(dir, file))
	if err != nil {
		log.Fatal(err)
	}
	if err := json.Unmarshal(b, v); err != nil {
		log.Fatalf("%s: %v", file, err)
	}
}

var colour = regexp.MustCompile(`^minecraft:(white|orange|magenta|light_blue|yellow|lime|pink|gray|light_gray|cyan|purple|blue|brown|green|red|black)_`)

// fallback lists stand-ins for an entry the old version lacks, best first. Blocks keep their shape
// (a client predicts collisions from the block it was sent); items keep their colour.
func fallback(registry, name string) []string {
	var out []string
	add := func(s ...string) { out = append(out, s...) }
	col := ""
	if m := colour.FindStringSubmatch(name); m != nil {
		col = m[1]
	}
	base := colour.ReplaceAllString(name, "minecraft:")
	switch {
	case strings.Contains(name, "poplar_leaves"):
		add("minecraft:birch_leaves", "minecraft:cherry_leaves")
	case strings.Contains(name, "poplar"):
		add(strings.ReplaceAll(name, "poplar", "birch"))
	}
	switch base {
	case "minecraft:concrete_slab", "minecraft:wool_slab":
		if registry == "minecraft:item" {
			add("minecraft:" + col + "_" + strings.TrimSuffix(strings.TrimPrefix(base, "minecraft:"), "_slab"))
		}
		add("minecraft:smooth_stone_slab")
	case "minecraft:concrete_stairs", "minecraft:wool_stairs":
		if registry == "minecraft:item" {
			add("minecraft:" + col + "_" + strings.TrimSuffix(strings.TrimPrefix(base, "minecraft:"), "_stairs"))
		}
		add("minecraft:stone_stairs")
	case "minecraft:shrub":
		add("minecraft:bush", "minecraft:short_grass")
	case "minecraft:cushion":
		if registry == "minecraft:item" {
			add("minecraft:" + col + "_carpet")
		}
	}
	switch {
	case name == "minecraft:shelf_mushroom":
		add("minecraft:brown_mushroom")
	case name == "minecraft:straw_bed":
		add("minecraft:white_bed")
	case registry == "minecraft:item" && strings.HasSuffix(name, "_map"):
		add("minecraft:map")
	}
	return out
}

func main() {
	oldDir := flag.String("old", "", "reports folder of the old version")
	newDir := flag.String("new", "", "reports folder of the new version")
	out := flag.String("out", "", "output file")
	pkg := flag.String("pkg", "", "package name")
	flag.Parse()
	if *oldDir == "" || *newDir == "" || *out == "" || *pkg == "" {
		flag.Usage()
		os.Exit(2)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by remapgen from Mojang's reports of both versions. DO NOT EDIT.\n\npackage %s\n\n", *pkg)

	// Packets.
	var po, pn packetsReport
	load(*oldDir, "packets.json", &po)
	load(*newDir, "packets.json", &pn)
	phases := []string{"configuration", "play"}
	for _, ph := range phases {
		cb := idTable(pn[ph]["clientbound"], po[ph]["clientbound"]) // new -> old
		sb := idTable(po[ph]["serverbound"], pn[ph]["serverbound"]) // old -> new
		name := strings.ToUpper(ph[:1]) + ph[1:]
		fmt.Fprintf(&b, "// clientbound%s maps a newest-version clientbound %s packet id to this version's (-1: none).\nvar clientbound%s = %s\n\n", name, ph, name, ints(cb))
		fmt.Fprintf(&b, "// serverbound%s maps this version's serverbound %s packet id to the newest version's (-1: none).\nvar serverbound%s = %s\n\n", name, ph, name, ints(sb))
	}
	for _, ph := range []string{"handshake", "status", "login"} {
		for _, dir := range []string{"clientbound", "serverbound"} {
			for k, v := range pn[ph][dir] {
				if o, ok := po[ph][dir][k]; !ok || o.ID != v.ID {
					log.Fatalf("%s %s %s changed: remap that phase too", ph, dir, k)
				}
			}
		}
	}

	// Block states.
	var bo, bn blocksReport
	load(*oldDir, "blocks.json", &bo)
	load(*newDir, "blocks.json", &bn)
	n := 0
	for _, blk := range bn {
		for _, st := range blk.States {
			n = max(n, int(st.ID)+1)
		}
	}
	states := make([]int32, n)
	var missing []string
	for name, blk := range bn {
		for _, st := range blk.States {
			id, ok := matchState(bo, name, st.Properties)
			if !ok {
				for _, alt := range fallback("minecraft:block", name) {
					if id, ok = matchState(bo, alt, st.Properties); ok {
						break
					}
				}
			}
			if !ok {
				id, _ = matchState(bo, "minecraft:stone", nil)
				missing = append(missing, name)
			}
			states[st.ID] = id
		}
	}
	fmt.Fprintf(&b, "// blockStates maps a newest-version block state to this version's.\nvar blockStates = %s\n\n", ints(states))

	// Built-in registries.
	var ro, rn registriesReport
	load(*oldDir, "registries.json", &ro)
	load(*newDir, "registries.json", &rn)
	var regs []string
	for r := range rn {
		if _, ok := ro[r]; ok {
			regs = append(regs, r)
		}
	}
	sort.Strings(regs)
	fmt.Fprintf(&b, "// builtin maps a newest-version id to this version's (-1: none), per built-in registry.\nvar builtin = map[string][]int32{\n")
	for _, r := range regs {
		size := 0
		for _, e := range rn[r].Entries {
			size = max(size, int(e.ID)+1)
		}
		t := make([]int32, size)
		for name, e := range rn[r].Entries {
			t[e.ID] = -1
			if o, ok := ro[r].Entries[name]; ok {
				t[e.ID] = o.ID
				continue
			}
			for _, alt := range fallback(r, name) {
				if o, ok := ro[r].Entries[alt]; ok {
					t[e.ID] = o.ID
					break
				}
			}
			if t[e.ID] == -1 && (r == "minecraft:item" || r == "minecraft:block" || r == "minecraft:entity_type" || r == "minecraft:particle_type") {
				missing = append(missing, r+" "+name)
			}
		}
		fmt.Fprintf(&b, "\t%q: %s,\n", r, ints(t))
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	sort.Strings(missing)
	log.Printf("%d block states; no stand-in for: %v", n, dedup(missing))
}

// idTable maps from's ids to to's ids by packet name.
func idTable(from, to map[string]struct {
	ID int32 `json:"protocol_id"`
}) []int32 {
	size := 0
	for _, p := range from {
		size = max(size, int(p.ID)+1)
	}
	t := make([]int32, size)
	for name, p := range from {
		t[p.ID] = -1
		if q, ok := to[name]; ok {
			t[p.ID] = q.ID
		}
	}
	return t
}

// matchState finds the state of block name with the given properties in an old report: an exact
// match, else the state that agrees on most of the properties they share (the default on a tie).
func matchState(r blocksReport, name string, props map[string]string) (int32, bool) {
	blk, ok := r[name]
	if !ok {
		return 0, false
	}
	best, bestScore := int32(-1), -1
	for _, st := range blk.States {
		score := 0
		for k, v := range props {
			if st.Properties[k] == v {
				score += 2
			}
		}
		if st.Default {
			score++
		}
		if score > bestScore {
			best, bestScore = st.ID, score
		}
	}
	return best, true
}

func ints(t []int32) string {
	var b strings.Builder
	b.WriteString("[]int32{")
	for i, v := range t {
		if i%24 == 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "%d,", v)
	}
	b.WriteString("\n}")
	return b.String()
}

func dedup(s []string) []string {
	var out []string
	for i, v := range s {
		if i == 0 || v != s[i-1] {
			out = append(out, v)
		}
	}
	return out
}
